# Generated by Django 4.1.7 on 2023-03-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_delete_room_remove_message_room_message_bot_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
    ]
